server:
  port: ${PORT:8080}

base-url: /api

spring:
  application:
    name: taskManager
  profiles:
    active: ${APP_ENV}

  liquibase:
#    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
