springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    username: ""
    password: ""
    url: "jdbc:h2:./taskManager"

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true
